spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/batch_db?serverTimezone=UTC
    username: user
    password: KeepItSimple1!
  batch:
    initialize-schema: always
app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/ratings_db?serverTimezone=UTC
    username: user
    password: KeepItSimple1!

